language: java
notifications:
  hipchat:
    rooms:
      secure: gNQkHj+fjYiz/5slfq7Yg4vXeWvSrI/PbYkFOjEaVeducGliiIkxZ05lnu67P8LADQJWN+RYTsX87VfhkrOlDcAExVcUwgjoJ5Bh/OgBKa2DsYLGa89e+J33O2T3ECvVRPN2ez4Tkc8VDDKtWVe0/vy6Pn+Nlw+I/ZeYAshvSbQ=
deploy:
  provider: releases
  api_key:
    secure: X4EP+c2rfVLizQCWmj849RmhngwuuoRQmUrQdu/OQbNfVPYNaH7WjNY1UKWBjqWYpTFhdBwBXnm2xfRVKB//uTI0tOV6yKpaXftz/BZ5JEm5on1rZBo2JmokzKc/D1LXWy0UqYfKekQ7lD+EwPsS0OlRxtRU4mZ8dHpPMoAgm48=
  file: build/distributions/xld-liquibase-plugin-5.0.1-SNAPSHOT.xldp
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-liquibase-plugin
    all_branches: true
    tags: true
